spring.application.name=BookReader
spring.datasource.url=jdbc:postgresql://localhost:5432/book_reader_db
spring.config.import=file:./secrets.properties

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
logging.level.com.example.bookreader=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
